# Where things are
source:          .
destination:     ./_site
collections_dir: .
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections:
  posts:
    output:   true

# Handling Reading
safe:                false
include:             [".htaccess"]
exclude:             ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "_ignore/"]
keep_files:          [".git", ".svn"]
encoding:            "utf-8"
markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: false
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
plugins:   []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      Europe/Paris

# Setup
title:            Pierre-Antoine ROBERT
tagline:          'TAGLINE'     #  TO MODIFY
description:      'DESCRIPTION' #  TO MODIFY
url:              http://www.parobert.com/
author: 'Pierre-Antoine ROBERT'
name:           'Pierre-Antoine ROBERT'
email:          pierreantoine.robert@gmail.com
paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
# google_analytics: UA-63207330-1 #  TO MODIFY
emailme:          mailto:pierreantoine.robert@gmail.com
github:
repo:           https://github.com/PARobert/blog.git
version:          March.1.2018
github_username:  parobert
linkedin_username: pierre-antoine-robert-9727a277
# twitter_username: 
# share_pdf: yes
# google_plus_username:
# instagram_username:
# facebook_username:
